### PR TITLE
ci: refacto quality check system

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by douglasduteil** [comment]
Aïe the images aren't working without **362Mb of node_modules** :kissing: :sweat_smile:

**Comment by douglasduteil** [comment]
:up: @revolunet @lionelB  Ready for review and merge :heart:

**Comment by lionelB** [comment]
@douglasduteil on peut merger ?

**Comment by douglasduteil** [comment]
:up: @revolunet @lionelB 
Boys I'm going to squash and merge this so it's ready and test releases on the master branch. I might have to push force the master if things does wrong... That's why I'm freezing the master on https://github.com/SocialGouv/code-du-travail-numerique/commit/dc7b5db29758c16c5707f00c777c72a1418028a6 (with a SAVE-master branch)

**Comment by lionelB** [comment]
wow merci!! 
greeeenn

**Pull request merged**
