### PR TITLE
test(e2e): add e2e tests

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by douglasduteil** [comment]
I'm extracting the `puppetteer` image to the common https://github.com/SocialGouv/docker repo

**Comment by revolunet** [comment]
Niiice ! 

can hardcoded pipeline trigger url be replaced with `${CI_API_V4_URL }/projects/${CI_PROJECT_ID}/trigger/pipeline`  ?

same for `CODECEPT_BASEURL` ?

also, shouldnt step* files be located in `optional/e2e/steps` ? (colocated with features)

**Comment by revolunet** [comment]
how to run this locally ?

**Comment by douglasduteil** [comment]
I added a little documentation @revolunet 
https://github.com/SocialGouv/code-du-travail-numerique/tree/douglasduteil/test-e2e-add-e2e-tests/optional/e2e

What do you think ?

**Comment by revolunet** [comment]
running tests ok but we could we add more info on how to write them ? `yarn run e2e` ?

how to write tests locally with a feedback loop ?

**Comment by douglasduteil** [comment]
@revolunet still needs more info on local writing & running ?

**Comment by douglasduteil** [comment]
Expected result here https://gitlab.factory.social.gouv.fr/SocialGouv/code-du-travail-numerique/pipelines/24201

**Comment by douglasduteil** [comment]
:up:

**Review by lionelB — APPROVED** [review]
thanks @douglasduteil

**Pull request merged**
