### PR TITLE
docs(README): update api usage

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by lionelB** [comment]
@douglas, why do we need to copy file on postbuild ?

**Comment by douglasduteil** [comment]
I think we should remove my hacky postbuild copy. It was necessary to make the build (dist/index.js) work locally. 
I think that the priority would be to make it work in the Dockerfile and document the additional needs in the README.

What you think @lionelB ?

PS : Tag me as @douglasduteil. Not @douglas
PPS : Sorry about the noise @douglas :pray:

**Comment by douglasduteil** [comment]
BTW we might want to try removing the whole hack as `ncc@0.20` and `elastic-apm-node@2.16` seems to more compatible 

Screenshot from 2019-08-29 09-41-00

**Comment by lionelB** [comment]
agree to remove ! I also add to update ncc in the PR #1089

**Review by lionelB — APPROVED** [review]

**Pull request merged**
