### PR TITLE
Added date and hour to title print page

### PR DESCRIPTION
**Pull request by nkrmr**
Added date and hour to title print page

[Calculer un préavis de démission le 06_12_2019 à 14_28.pdf](https://github.com/SocialGouv/code-du-travail-numerique/files/3932443/Calculer.un.preavis.de.demission.le.06_12_2019.a.14_28.pdf)

### CODE REVIEW

**Review by lionelB — APPROVED** [review]

**Comment by revolunet** [comment]
you may ensure the title is updated only once if for some reason the user clicks multiple time

**Comment by nkrmr** [comment]
@revolunet  I set again title with the original just after the print

**Comment by revolunet** [comment]
true my bad :)

**Review by revolunet — APPROVED** [review]

**Comment by nkrmr** [comment]
cf: #1839

**Pull request merged**
