### PR TITLE
fix(frontend): return mock of return data on outils fetch error

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Review by lionelB — CHANGES_REQUESTED** [review]
You should add a comment of  why you choose to fail silently rather than handle the error

**Comment by douglasduteil** [comment]
> why you choose to fail silently rather than handle the error

This is handling the error.
If you `throw` the code stops and the user can't see a thing.
It's unknown to me if we catch all errors in the browser to a logstash or sth
by returning a similar structure with no data it's activating the "Big Error" flow [giving the user a not found response](
https://github.com/SocialGouv/code-du-travail-numerique/pull/313/files#diff-4fd0387f53cc8b097c46a03246a8f7ebR37)

**Comment by douglasduteil** [comment]
I actually changed that to test my PR with the Alert code ;)

**Comment by lionelB** [comment]
> If you throw the code stops and the user can't see a thing.
In fact, throwing the error shown the error page

**Comment by douglasduteil** [comment]
> In fact, throwing the error shown the error page

Alright. Is it the 500 error page ? Is it better than the error in the context ?!
Tested with https://codedutravail.num.social.gouv.fr/outils/sdf

**Comment by lionelB** [comment]
well is is, but it should be 404 :)
ok to use the in context error

Le lun. 26 nov. 2018 à 14:58, Douglas Duteil <notifications@github.com> a
écrit :

**Comment by douglasduteil** [comment]
> well is is, but it should be 404 :)

Should I still add a `console.error(e)` ?
How do we log error from user land back to us ?

**Comment by lionelB** [comment]
@douglasduteil  we should add sentry to log error. 
I propose to use console.error for now, and create a PR to add sentry client and get rid of all console.error. what do you think ?

**Review by lionelB — APPROVED** [review]

**Pull request merged**
