### PR TITLE
feature(ui): add table component

### PR DESCRIPTION
**Pull request by UnbearableBear**
You can view it here: https://socialgouv.github.io/code-du-travail-numerique/

### CODE REVIEW

**Comment by lionelB** [comment]
yeah !

**Review by lionelB — COMMENTED** [review]
What do you think about adding a props ~`zebra`~  `striped` (not sure about the name) whicj will add odd/event background coloring ?

**Comment by UnbearableBear** [comment]
Let's do it

**Comment by lionelB** [comment]
can you update the styleguide ?

**Comment by UnbearableBear** [comment]
Which kind of update do you want ?

**Comment by lionelB** [comment]
@UnbearableBear you add an example of stripe table but the link above doesn't seems to be up to date (https://socialgouv.github.io/code-du-travail-numerique/table-doc)

**Review by lionelB — APPROVED** [review]

**Pull request merged**
