### PR TITLE
chore(frontend): remove next-plugin-transpile-modules

### PR DESCRIPTION
**Pull request by lionelB**
next-plugin-transform-module broke reload from `packages/*` files (eg updatating css need a next restart :/ )
I create a local copy of pDebounce so it will be transpile

### CODE REVIEW

**Comment by douglasduteil** [comment]
This is bad...
We should avoid copy pasting node_modules in our code.
Are they other solutions ?

**Comment by revolunet** [comment]
Upstream pull request ?

**Comment by douglasduteil** [comment]
Upstream => next-plugin-transform-module ?
Ou 
Upstream => pDebounce ?

**Comment by lionelB** [comment]
I try to make next-plugin-transpile-module works without success so bafore wasting to much time, I prefer fix the problem we actually have (css update need next to restart) and figure a better solution

**Comment by revolunet** [comment]
sent a PR to upstream project and... got rejected :) https://github.com/sindresorhus/p-debounce/pull/4

there are some alternatives like https://github.com/bjoerge/debounce-promise

**Comment by lionelB** [comment]
For the record, babel-engine-plugin not work for ie, so I leave it with code duo. I think p-debounce should not evolve that much

**Comment by lionelB** [comment]
@douglasduteil  est ce qu'on peut merger ?

**Review by revolunet — APPROVED** [review]

**Pull request merged**
