### PR TITLE
refactor(chore): add root linter

### PR DESCRIPTION
**Pull request by UnbearableBear**
C'est une bonne idée ça ?

### CODE REVIEW

**Review by lionelB — COMMENTED** [review]
there is obviously some changes that aren't related to moving a file

**Comment by UnbearableBear** [comment]
These are files that got formated because of the linting changes. But it seems that the CI is not liking that

**Comment by lionelB** [comment]
I think it will be more usefull to add a generic config a the top and ovverife it in project (ie a11y rules are only usefull in frontend)

**Pull request closed without merging**
