### PR TITLE
refactor(css): migrate global styles to frontend app

### PR DESCRIPTION
**Pull request by UnbearableBear**
We are almost done with this css subrepo, almost !

### CODE REVIEW

**Review by lionelB — CHANGES_REQUESTED** [review]
@UnbearableBear can you add snapshots ?

**Comment by UnbearableBear** [comment]
@lionelB You mean screenshots ? because they are no diff in the snapshots

**Comment by lionelB** [comment]
@UnbearableBear you ned to add a snapshot for the GlobalStyle component

**Comment by UnbearableBear** [comment]
@lionelB Nice catch, I added it (even if it's empty) and I also split the global style in smaller files. I had an issue with styled components and the inline svg so I used a base64 encoding to avoid that https://github.com/styled-components/jest-styled-components/issues/97

**Review by lionelB — APPROVED** [review]

**Pull request merged**
