### PR TITLE
ci: simplify travis stages to handle pr first

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by douglasduteil** [comment]
\ping @Virasack

**Comment by lionelB** [comment]
@douglasduteil ~ is it still relevant ? ~  of course :) it's not gitlab-ci but travis-ci

**Review by lionelB — APPROVED** [review]
sounds good :) 
To clarify, for PR from forks, only the travis-ci will run, or gitlab will also run ?

**Comment by lionelB** [comment]
UP!

**Comment by douglasduteil** [comment]
> To clarify, for PR from forks, only the travis-ci will run, or gitlab will also run ?

GitLab never run for PR from forks.
Travis here is set to handle all PRs.
And the release process too ;)

**Comment by douglasduteil** [comment]
Can be revert if needed :)

**Pull request merged**
