### PR TITLE
build(docker): update to node:14.16-alpine3.13

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Review by lionelB — APPROVED** [review]
This is the only node docker image ? I though we have others

**Comment by douglasduteil** [comment]
> This is the only node docker image ? I though we have others

Found more I'm updating

**Comment by douglasduteil** [comment]
🆙 @lionelB :)

**Comment by douglasduteil** [comment]
Linked to  #3334

**Review by lionelB — APPROVED** [review]
lgtm

**Comment by douglasduteil** [comment]
@lionelB is it normal that we do not have apis in dev envs ?
https://b72bda3-code-travail.dev2.fabrique.social.gouv.fr/recherche?q=cdi
https://api-master-code-travail.dev2.fabrique.social.gouv.fr/api/v1/search?q=cdi

**Comment by lionelB** [comment]
> @lionelB is it normal that we do not have apis in dev envs ?

what do you mean ? api don't return results ?

**Pull request merged**
