### PR TITLE
feat(matomo): add suggestionCandidate and resultsCandidate in matomo

### PR DESCRIPTION
**Pull request by lionelB**
better tracking of provided info to user
- send candidateResults when display a SERP (Search Engine Result Page)
- send candidateSuggestion when clicking a suggestion.
- handle campaign id
- log back to results
- log selectResult 

this will help us better know what suggestions are better clicked 

ref #1624

### CODE REVIEW

**Comment by revolunet** [comment]
Not sure this is a good idea to push every results and suggestions to the user and back to the server; cant we extract these at "logs pipeline" level ?

**Comment by lionelB** [comment]
> cant we extract these at "logs pipeline" level ?

that's what was done but its also ended with weird results when trying to consolidate those logs. 
@rmelisson and @ArmandGiraud ask for it, so I leave them to better explain the why :)

**Comment by ArmandGiraud** [comment]
> cant we extract these at "logs pipeline" level ?

We can, but sending the suggestions and result list directly in Matomo avoids errors in the logs pipeline. Secondly it avoids to make all requests twice, as it is not necessary 🌎.
@revolunet  Why do you think it's not a good idea to send it?

**Comment by revolunet** [comment]
it just sounds weird to send the results to the user and then send them back to us... also, network and performance from a user perspective :) also as a user i wont be very happy to see this in my network logs...
BTW we need reliability on the data so if we cant reproduce the results on our side we dont have much choice....

**Review by revolunet — APPROVED** [review]

**Pull request merged**
