### PR TITLE
doc(app):Updated README file with new populate NLP command

### PR DESCRIPTION
**Pull request by nkrmr**
Updated README file with new populate NLP API command:

```sh
# Populate data to nlp api
$ docker run --rm --entrypoint cat registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/data:0d5b8065ca7df8b62827108f61e7168c4581c3ea  /app/dump.tf.json  > ./packages/code-du-travail-nlp/data/dump.data.json
```

### CODE REVIEW

**Review by revolunet — APPROVED** [review]

**Comment by revolunet** [comment]
at some point we should use "latest" or "master" instead of the commit SHA... but these images are not available... yet

**Comment by lionelB** [comment]
@revolunet t using `git rev-parse origin/master` you can retrieve the sha ;)
```sh
$CDTN_REGISTRY=registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique 
$ docker run \
        --rm \
        --entrypoint cat $CDTN_REGISTRY/data:$(git rev-parse origin/master)/app/dump.tf.json \ 
        > ./packages/code-du-travail-nlp/data/dump.data.json
```

**Comment by lionelB** [comment]
Can you put this command under a howto section ?

**Comment by lionelB** [comment]
So we can add other usefull docker commands

**Comment by nkrmr** [comment]
Sure

**Review by UnbearableBear — APPROVED** [review]

**Review by lionelB — APPROVED** [review]
LGTM !

**Pull request closed without merging**
