### PR TITLE
Fixed input search submit event

### PR DESCRIPTION
**Pull request by nkrmr**
Fixed  IE11 issue to submit event on input search Cf: #1988

### CODE REVIEW

**Review by UnbearableBear — APPROVED** [review]
IE 11 et ses merdouilles ...

**Comment by UnbearableBear** [comment]
Ca marche bien en local sur ta branche sous ie11, welle done !

**Review by lionelB — APPROVED** [review]

**Review by lionelB — COMMENTED** [review]
I wonder If could simplify it by doing only form.submit() + ie11 event hack

**Comment by nkrmr** [comment]
It's to keep compatibility to old browsers

**Comment by lionelB** [comment]
> It's to keep compatibility to old browsers ? 

we don't support older browser than ie10  I think

**Pull request merged**
