### PR TITLE
added .vscode to .gitignore

### PR DESCRIPTION
**Pull request by adipasquale**

### CODE REVIEW

**Comment by UnbearableBear** [comment]
Et il y a quoi dans ton dossier .vscode ? 🤓

**Comment by adipasquale** [comment]
screen shot 2019-02-19 at 16 18 41

vive la 🇫🇷

**Review by douglasduteil — CHANGES_REQUESTED** [review]
For me, the `.gitignore` in a project should be configured for the project itself, not the environment nor the IDE nor the os.
IDE folder should be be in your global `.gitignore` file.

For example, I use my user folder as root : 

https://github.com/douglasduteil/dotfiles/blob/c4c6428f2f7550d103027638489f61664e959d87/git/.gitconfig#L5

For my globlal gitignore file https://github.com/douglasduteil/dotfiles/blob/c4c6428f2f7550d103027638489f61664e959d87/git/.gitignore_global

**Review by douglasduteil — CHANGES_REQUESTED** [review]
For me, the `.gitignore` in a project should be configured for the project itself, not the environment nor the IDE nor the os.
IDE folder should be be in your global `.gitignore` file.

For example, I use my user folder as root : 

https://github.com/douglasduteil/dotfiles/blob/c4c6428f2f7550d103027638489f61664e959d87/git/.gitconfig#L5

For my globlal gitignore file https://github.com/douglasduteil/dotfiles/blob/c4c6428f2f7550d103027638489f61664e959d87/git/.gitignore_global

**Comment by adipasquale** [comment]
alright that makes sense, I didn't even know I had a global .gitignore file, I'll use that. thanks @douglasduteil

**Comment by douglasduteil** [comment]
You are welcome :)

**Pull request closed without merging**
