### PR TITLE
feat(chore): update readme

### PR DESCRIPTION
**Pull request by UnbearableBear**

### CODE REVIEW

**Comment by UnbearableBear** [comment]
Encore deux ou trois améliorations à faire, c'est encore un draft mais si vous voulez validez c'est gentil :D

**Review by revolunet — APPROVED** [review]

**Review by lionelB — DISMISSED** [review]
as sub readme tend to not being read, I would enforce a howto / faq section in the main Readme et merge sub readme

**Review by nkrmr — APPROVED** [review]

**Comment by lionelB** [comment]
don't forget to fix codecov, before merging

**Comment by lionelB** [comment]
> Lionel is a very busy man ! 
or Manu is a hurry man ;)

**Comment by UnbearableBear** [comment]
🤣

**Pull request merged**
