### PR TITLE
chore(frontend): allow node_modules transpilation for some modules

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by douglasduteil** [comment]
Related to future Typescript PR

**Comment by lionelB** [comment]
@douglasduteil can you fix the conflict ?

**Comment by douglasduteil** [comment]
:up: missing yarn.lock i think...

**Review by revolunet — APPROVED** [review]

**Comment by lionelB** [comment]
@douglasduteil  have you seen this issue 
https://github.com/martpie/next-plugin-transpile-modules/issues/1

**Comment by douglasduteil** [comment]
> @douglasduteil have you seen this issue

No. Would you like us to update to the latest dependencies version before merging this ?

**Comment by douglasduteil** [comment]
Too old now

**Pull request closed without merging**
