### PR TITLE
lpiot/docker compose fix

### PR DESCRIPTION
**Pull request by lpiot**
I'm currently working on migration from `docker-compose` to `Kubernetes`.
To do so, first and foremost, I'm trying to run the `docker-compose` such as the `README.md` file explains it.
Met few minor bugs.

### CODE REVIEW

**Comment by lionelB** [comment]
hello @lpiot 
before going too far, you should take a look a the incoming PR (https://github.com/SocialGouv/code-du-travail-numerique/pull/312) which should be merge in few day and which also update docker file.

**Comment by revolunet** [comment]
suggestion for a smaller test : https://github.com/SocialGouv/socialgouv.github.io/

**Comment by revolunet** [comment]
fix some issue with `docker-compose --build`

capture d ecran 2018-12-07 a 17 14 05 1

**Comment by revolunet** [comment]
thanks @lpiot

**Review by revolunet — APPROVED** [review]

**Pull request merged**
